name: Build & Deploy Frontend

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  S3_KEY: ${{ vars.PIPELINE_FRONTEND_KEY }}

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # for debugging OIDC token
      # - name: Show OIDC context
      #   run: |
      #     echo "ref=$GITHUB_REF"
      #     echo "workflow_ref=$GITHUB_WORKFLOW_REF"
      # - name: Debug OIDC token (default audience)
      #   run: |
      #     ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
      #     echo "$ID_TOKEN" | base64

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            frontend/package-lock.json
            infra/package-lock.json

      - run: npm ci
        working-directory: frontend
      - run: npm test --if-present
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
        env:
          NEXT_PUBLIC_FIELD_MAX: ${{ secrets.NEXT_PUBLIC_FIELD_MAX }}
          NEXT_PUBLIC_COMMENT_MAX: ${{ secrets.NEXT_PUBLIC_COMMENT_MAX }}
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_USE_DEMO_AUTH: ${{ secrets.NEXT_PUBLIC_USE_DEMO_AUTH }}
      - run: test -d out
        working-directory: frontend

      # - name: Configure AWS creds (OIDC)
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Deploy to S3
      #   run: aws s3 sync ./out "s3://${{ secrets.FRONTEND_BUCKET }}/" --delete
      #   working-directory: frontend

      # - name: Invalidate CloudFront
      #   run: aws cloudfront create-invalidation --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" --paths "/*"

      # put together the published artifacts into a zip file
      - name: Package frontend build
        run: zip -r frontend-artifacts.zip out
        working-directory: frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3
        run: aws s3 cp frontend-artifacts.zip "s3://${{ vars.PIPELINE_SOURCE_BUCKET }}/${{ env.S3_KEY }}"
        working-directory: frontend
